language: csharp

os: linux
dist: trusty
group: edge
sudo: required
mono: latest
dotnet: 2.0.0

script:
- sudo nuget update -self
- nuget pack Syncromatics.Engineering.DX.Common.nuspec -Version ${TRAVIS_TAG:-0.0.0-$TRAVIS_COMMIT-$TRAVIS_EVENT_TYPE-$TRAVIS_BUILD_NUMBER}

deploy:
  provider: script
  script:
  - dotnet nuget push Syncromatics.Engineering.DX.Common.$TRAVIS_TAG.nupkg -s https://www.nuget.org/api/v2/package -k $NUGET_API_KEY
  on: 
    tags: true