language: csharp

os: linux
dist: trusty
group: edge
sudo: required
mono: latest
dotnet: 2.0.0

before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe

script:
- mono .nuget/nuget.exe pack Syncromatics.Engineering.DX.Common.nuspec -Version ${TRAVIS_TAG:-0.0.0-$TRAVIS_COMMIT-$TRAVIS_BUILD_NUMBER}

deploy:
  provider: script
  skip_cleanup: true
  script:
  - dotnet nuget push Syncromatics.Engineering.DX.Common.*.nupkg -s https://www.nuget.org/api/v2/package -k $NUGET_API_KEY
  on: 
    tags: true